//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyBrinkEmployee_Student_Teacher_Staff_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revenue
    {
        public int Id { get; set; }
        public string Department { get; set; }
        public string Profit { get; set; }
        public string Year { get; set; }
    }
}
